CourseWork/Models/Suggestion.cs
using System.ComponentModel.DataAnnotations;

namespace CourseWork.Models;

public class Suggestion
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    
    [Required(ErrorMessage = "Не указана тема")]
    [Display(Name = "Тема")]
    public string Theme { get; set; }
    
    [Required(ErrorMessage = "Не указан описание")]
    [Display(Name = "Описание")]
    public string Text { get; set; }
    
    public byte[]? ImageData { get; set; }
    
    public DateTime CreationDate { get; set; } = DateTime.Now;
}

CourseWork/Controllers/SuggestionController.cs
using CourseWork.Models;
using CourseWork.Services;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

public class SuggestionController : Controller
{
    private readonly ISuggestionService _suggestionService;

    public SuggestionController(ISuggestionService suggestionService)
    {
        _suggestionService = suggestionService;
    }

    public IActionResult Suggestions() => View(_suggestionService.Suggestions);
    
    public IActionResult CreateSuggestion()
    {
        return View(new Suggestion());
    }
    
    [HttpPost]
    public async Task<IActionResult> CreateSuggestion(Suggestion suggestion, IFormFile? image = null)
    {
        if (!ModelState.IsValid)
            return View(suggestion);

        if (image != null)
        {
            using (var binaryReader = new BinaryReader(image.OpenReadStream()))
            {
                suggestion.ImageData = binaryReader.ReadBytes((int)image.Length);
            }
        }
        
        await _suggestionService.AddAsync(suggestion);
        return RedirectToAction("Index", "Home");
    }

    public IActionResult SuggestionInfo(Guid suggestionId)
    {
        var suggestion = _suggestionService.GetByIdAsync(suggestionId).Result;
        return View(suggestion);
    }
    
    public async Task<IActionResult> DeleteSuggestion(Guid? suggestionId)
    {
        var suggestion = _suggestionService.GetByIdAsync(suggestionId).Result;
        if (suggestion != null)
        {
            await _suggestionService.DeleteAsync(suggestionId);
        }
        
        return RedirectToAction("Suggestions");
    }
}

CourseWork/Views/Suggestion/CreateSuggestion.cshtml
@model Suggestion

@{
    Layout = "_Layout";
}

<h2>Форма для ваших предложений!</h2>
<form class="row g-3" method="post" asp-controller="Suggestion" asp-action="CreateSuggestion" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly"></div>
    <input type="hidden" asp-for="Id">
    <input type="hidden" asp-for="CreationDate">
    <div class="col-12">
        <label class="form-label" asp-for="Theme"></label><br />
        <input class="form-control" asp-for="Theme" />
        <span asp-validation-for="Theme"></span>
    </div>
    <div class="col-12">
        <label class="form-label" asp-for="Text"></label><br />
        <textarea  class="form-control" asp-for="Text"></textarea>
        <span asp-validation-for="Text"></span>
    </div>
    <div class="col-12">
        <label  class="control-label">Изображение</label>
        <input type="file" name="image" class="form-control" />
    </div>
    <div>
        <input class="btn btn-outline-dark" type="submit" value="Отправить" />
    </div>
</form> 

CourseWork/Views/Suggestion/SuggestionInfo.cshtml
@model CourseWork.Models.Suggestion?

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="ru">
<head>
    <title>Информация о предложении</title>
</head>
<body>
<div>
    <h4>@Model.Theme</h4>
    @if (Model?.ImageData != null)
    {
        <img style='width:800px; display: block; margin-left: auto; margin-right: auto;' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.ImageData))" alt="image"/>
    }
    <dl class="row">
        <dt class="col-sm-3">Описание:</dt>
        <dd class="col-sm-9"><p>@Model.Text</p></dd>

        <dt class="col-sm-3">Дата добавления:</dt>
        <dd class="col-sm-9">@Model.CreationDate</dd>
    </dl>
</div>
</body>
</html>

CourseWork/Views/Suggestion/Suggestions.cshtml
@model System.Linq.IQueryable<CourseWork.Models.Suggestion>

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="ru">
<head>
    <title>Просмотр предложений</title>
</head>
<body>
<div>
      @if (!Model.Any())
      {
          <li class="list-group-item">Предложений нет</li>
      }
      else
      {
          <table class="table">
              <thead>
                  <tr>
                      <th scope="col">№</th>
                      <th scope="col">Тема</th>
                      <th scope="col">Дата добавления</th>
                      <th scope="col">Информация</th>
                      <th scope="col"></th>
                  </tr>
              </thead>
              <tbody>
              @{var counter = 0;    
                  foreach (var suggestion in Model)
                  {
                      counter++;
                      <tr>
                          <th scope="row">@counter</th>
                          <td>@suggestion.Theme</td>
                          <td>@suggestion.CreationDate</td>
                          <td>
                              <a class="btn btn-sm btn-outline-primary" asp-route-suggestionId="@suggestion.Id" asp-controller="Suggestion" asp-action="SuggestionInfo">Подробнее</a>
                          </td>
                          <td>
                              <a class="btn btn-sm btn-outline-danger" asp-route-suggestionId="@suggestion.Id" asp-controller="Suggestion" asp-action="DeleteSuggestion">Удалить</a>
                          </td>
                      </tr>
                  }
              }
              </tbody>
          </table>
      }
</div>
</body>
</html>