CourseWork/Models/Test.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Models;

public class Test
{
    [Key]
    public Guid Id { get; set; }
    public string Category { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    [BindProperty, DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm}", ApplyFormatInEditMode = true)]
    public DateTime OpenTime { get; set; }
    [BindProperty, DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm}", ApplyFormatInEditMode = true)]
    public DateTime CloseTime { get; set; }
    public int QuestionsCount { get; set; }
    public int QuestionsLimit { get; set; }
    public bool ShuffleQuestions { get; set; }
    
    public IEnumerable<Question>? Questions { get; set; }
    public IEnumerable<UserResult>? UserResults { get; set; }
}

CourseWork/ViewModels/CreateTestViewModel.cs
using CourseWork.Models;
using CourseWork.Models.Enums;

namespace CourseWork.ViewModels;

public class CreateTestViewModel
{
    public Guid TestId { get; set; } = Guid.NewGuid();
    public string Category { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public DateTime OpenTime { get; set; }
    public DateTime CloseTime { get; set; }
    public int QuestionsLimit { get; set; }
    public bool ShuffleQuestions { get; set; }
    public List<Question> Questions { get; set; } = new();
    public List<QuestionType> Types { get; set; } = new();

    public CreateTestViewModel()
    {
        foreach (var type in Enum.GetValues(typeof(QuestionType)))
        {
            Types.Add((QuestionType)type);
        }
    }
}

CourseWork/ViewModels/EditTestViewModel.cs
using CourseWork.Models;
using CourseWork.Models.Enums;

namespace CourseWork.ViewModels;

public class EditTestViewModel
{
    public Guid TestId { get; set; }
    public string Category { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public DateTime OpenTime { get; set; }
    public DateTime CloseTime { get; set; }
    public int QuestionsLimit { get; set; }
    public int QuestionsCount { get; set; }
    public bool ShuffleQuestions { get; set; }
    public List<Question> Questions { get; set; }
    public List<QuestionType> Types { get; set; } = new();

    public EditTestViewModel()
    {
        foreach (var type in Enum.GetValues(typeof(QuestionType)))
        {
            Types.Add((QuestionType)type);
        }
    }
}

CourseWork/Controllers/AdminController.cs
using System.Transactions;
using CourseWork.Models;
using CourseWork.Services;
using CourseWork.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

[Authorize(Roles="admin, tutor")]
public class AdminController : Controller
{
    private readonly ITestService _testService;
    private readonly IQuestionService _questionService;
    private readonly IAnswerService _answerService;
    
    public AdminController(ITestService testService, IQuestionService questionService, IAnswerService answerService)
    {
        _testService = testService;
        _questionService = questionService;
        _answerService = answerService;
    }
    
    public IActionResult Tests() => View(_testService.Tests);

    [HttpGet]
    public IActionResult CreateTest()
    {
        return View(new CreateTestViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> CreateTest(CreateTestViewModel model)
    {
        if (!ModelState.IsValid) return View(model);
        
        var test = new Test 
        { 
            Id = model.TestId,
            Category = model.Category, Name = model.Name, 
            Description = model.Description, OpenTime = model.OpenTime, 
            CloseTime = model.CloseTime, QuestionsCount = model.Questions.Count,
            QuestionsLimit = model.QuestionsLimit,
            ShuffleQuestions = model.ShuffleQuestions,
            Questions = model.Questions.AsEnumerable()
        };

        await _testService.AddAsync(test);
        return RedirectToAction("Tests");
    }
    
    [HttpGet]
    public async Task<IActionResult> EditTest(Guid? testId)
    {
        if (testId == null) return NotFound();
        var test = await _testService.GetByIdAsync(testId);
        if (test == null) return NotFound();
        var model = new EditTestViewModel
        {
            TestId = test.Id,
            Category = test.Category, Name = test.Name,
            Description = test.Description,
            OpenTime = test.OpenTime, CloseTime = test.CloseTime,
            QuestionsLimit = test.QuestionsLimit,
            QuestionsCount = test.QuestionsCount,
            ShuffleQuestions = test.ShuffleQuestions,
            Questions = _questionService.Questions.Where(q => q.TestId == test.Id).OrderBy(q => q.Number).ToList(),
        };
        
        foreach (var question in model.Questions)
        {
            question.Answers = _answerService.Answers.Where(a => a.QuestionId == question.Id).OrderBy(a => a.Number).ToList();
        }
        return View(model);
    }
    
    [HttpPost]
    public async Task<IActionResult> EditTest(EditTestViewModel model)
    {
        if (!ModelState.IsValid) return View(model);
        var test = await _testService.GetByIdAsync(model.TestId);
        if (test == null) return View(model);
        
        using (var scope = new TransactionScope(
                   TransactionScopeAsyncFlowOption.Enabled))
        {
            await _testService.DeleteAsync(test.Id).ConfigureAwait(false);
            scope.Complete();
        }
        
        test.Category = model.Category;
        test.Name = model.Name;
        test.Description = model.Description;
        test.OpenTime = model.OpenTime;
        test.CloseTime = model.CloseTime;
        test.QuestionsLimit = model.QuestionsLimit;
        test.QuestionsCount = model.Questions.Count;
        test.Questions = model.Questions.AsEnumerable();
        test.ShuffleQuestions = model.ShuffleQuestions;

        using (var scope = new TransactionScope(
                   TransactionScopeAsyncFlowOption.Enabled))
        {
            await _testService.AddAsync(test).ConfigureAwait(false);
            scope.Complete();
        }

        return RedirectToAction("Tests");
    }
    
    public async Task<IActionResult> DeleteTest(Guid? testId)
    {
        if (testId == null) return NotFound();
        await _testService.DeleteAsync(testId);
        return RedirectToAction("Tests");
    }
}

CourseWork/Controllers/NotificationController.cs
using System.Net;
using System.Net.Mail;
using CourseWork.Constants;
using CourseWork.Models;
using CourseWork.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

public class NotificationController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly ITestService _testService;
    
    public NotificationController(UserManager<User> userManager, ITestService testService)
    {
        _userManager = userManager;
        _testService = testService;
    }

    public IActionResult ConfigureNotifications(Guid testId)
    {
        ViewData["testId"] = testId;
        var users = _userManager.GetUsersInRoleAsync("student").Result;
        users = users.OrderBy(u => u.UserName).ThenBy(u => u.Group).ToList();
        return View(users.ToList());
    }
    
    [HttpPost]
    public async Task<IActionResult> ConfigureNotifications(List<string> emails, Guid testId, string? comment)
    {
        var test = _testService.Tests.FirstOrDefault(t => t.Id == testId);
        if (test == null)
            return RedirectToAction("Index", "Test");
        
        foreach (var email in emails)
        {
            await SendEmail(email, comment, test);
        }
        return RedirectToAction("Index", "Test");
    }

    private async Task SendEmail(string email, string? comment, Test test)
    {
        var from = new MailAddress(NotificationConstants.EmailFrom, "Предстоящее тестирование");
        var to = new MailAddress(email);
        var message = new MailMessage(from, to);

        message.Subject = $"Тестирование по дисциплине \"{test.Category}\"";
        message.Body = GetMessage(test);
        if (!string.IsNullOrEmpty(comment?.Trim()))
        {
            message.Body += "<p>Комментарий преподавателя:\t" + comment +"<p>";
        }
        message.IsBodyHtml = true;
        
        var smtp = new SmtpClient(NotificationConstants.GmailHost, NotificationConstants.GmailPort);
        smtp.Credentials = new NetworkCredential(NotificationConstants.EmailFrom, NotificationConstants.Password);
        smtp.EnableSsl = true;
        await smtp.SendMailAsync(message);
    }

    private string GetMessage(Test test)
    {
        return "<h4>Информация о тестировании</h4>" +
               "<p>Вы записаны на прохождение тестирования по дисциплине \"" + 
               test.Category + "\". Это автоматическое уведомление от системы тестирования.</p>" +
               "<p><b>Время начала тестирования:</b>\t\t" + test.OpenTime + "</p>" +
               "<p><b>Время окончания тестирования:</b>\t" + test.CloseTime + "</p>" +
               "<p><b>Описание:</b>\t<p>" + test.Description + "</p> </p>" +
               "<p><b>Вопросов в тесте:</b>\t\t\t" + test.QuestionsLimit + "</p>" +
               "<p>Ссылка на тест: testingsystems.com/tests/testInfo/" + test.Id + "</p>";
    }
}

CourseWork/Controllers/TestController.cs
using CourseWork.Extensions;
using CourseWork.Models;
using CourseWork.Services;
using CourseWork.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

[Authorize]
public class TestController : Controller
{
    private readonly ITestService _testService;
    private readonly IAnswerService _answerService;
    private readonly IQuestionService _questionService;
    private readonly IUserResultService _userResultService;
    private readonly UserManager<User> _userManager;
    
    public TestController(ITestService testService, IAnswerService answerService, 
        UserManager<User> userManager, IQuestionService questionService, IUserResultService userResultService)
    {
        _testService = testService;
        _answerService = answerService;
        _userManager = userManager;
        _questionService = questionService;
        _userResultService = userResultService;
    }

    public IActionResult Index()
    {
        var tests = _testService.Tests.OrderByDescending(t => t.OpenTime).ToList();
        var sorted = tests.Where(t => DateTime.Now < t.CloseTime).OrderBy(t => t.OpenTime).ToList();
        sorted.AddRange(tests.Where(t => DateTime.Now > t.CloseTime).OrderByDescending(t => t.OpenTime).ToList());
        return View(sorted);
    }

    public async Task<IActionResult> TestInfo(Guid? testId) => View(await _testService.GetByIdAsync(testId));

    public async Task<IActionResult> Testing(Guid testId, QuestionViewModel model, int currentPage = 1)
    {
        var test = await _testService.GetByIdAsync(testId);
        if (test == null)
        {
            return RedirectToAction("Index", "Home");
        }
        
        if (DateTime.Now < test.OpenTime || DateTime.Now > test.CloseTime)
        {
            TempData["error-message"] = "В доступе отказано";
            return RedirectToAction("TestInfo", new {testId = test.Id});
        }

        if (model.UserAnswers.Any() && model.Answers.Any())
        {
            if (model.SelectedUserAnswerId != null)
            {
                model.UserAnswers
                    .Where(a => a.Id == model.SelectedUserAnswerId)
                    .ToList().ForEach(a => a.IsCorrect = true);
            }
            UpdateUserResult(model.UserAnswers, model.Answers, test, model.Question.Cost);
        }

        const int pageSize = 1;
        var questions = GetQuestions(test);
        var question = questions.Skip((currentPage - 1) * pageSize).Take(pageSize).FirstOrDefault();
        if (question == null)
        {
            return RedirectToAction("Error", "Home");
        }
        var answers = _answerService.Answers.Where(a => a.QuestionId == question.Id).ToList();
        var userAnswers = new List<UserAnswer>();
        
        for (var i = 0; i < answers.Count; i++)
        {
            userAnswers = userAnswers.Append(new UserAnswer
            {
                QuestionNumber = question.Number
            }).ToList();
        }
        
        return View(new QuestionViewModel
        {
            Question = question, 
            UserAnswers = userAnswers,
            Answers = answers,
            TestCloseTime = test.CloseTime,
            PageViewModel = new PageViewModel(test.QuestionsLimit, currentPage, pageSize)
        });
    }

    public void UpdateUserResult(List<UserAnswer> userAnswers, List<Answer> correctAnswers, Test test, int cost)
    {
        var userId = _userManager.GetUserId(HttpContext.User);
        var userResult = GetUserResult(test.Id, userId, test.QuestionsLimit);
        userResult.AddAnswers(userAnswers, correctAnswers, cost);
        SaveUserResult(userResult);
    }

    public async Task<IActionResult> EndTesting(QuestionViewModel model)
    {
        var test = await _testService.GetByIdAsync(model.Question.TestId);
        if (test == null)
        {
            return RedirectToAction("Index", "Home");
        }

        UpdateUserResult(model.UserAnswers, model.Answers, test, model.Question.Cost);

        var userId = _userManager.GetUserId(HttpContext.User);
        var userResult = GetUserResult(model.Question.TestId, userId, test.QuestionsLimit);
        await _userResultService.AddAsync(userResult);
        HttpContext.Session.Clear();
        ViewData["userResultId"] = userResult.Id;
        return View(userResult);
    }

    [HttpPost]
    public IActionResult BackToTests(Guid userResultId, string? comment)
    {
        if (string.IsNullOrEmpty(comment?.Trim())) 
            return RedirectToAction("Index");
        
        var userResult = _userResultService.UserResults.FirstOrDefault(r => r.Id == userResultId);
        if (userResult != null)
        {
            userResult.UserComment = comment;
            _userResultService.UpdateAsync(userResult);
        }
        return RedirectToAction("Index");
    }
    
    private IEnumerable<Question> GetQuestions(Test test)
    {
        var questions = HttpContext.Session.GetJson<IEnumerable<Question>>("Questions");
        if (questions != null) return questions;

        questions = _questionService.Questions.Where(q => q.TestId == test.Id).OrderBy(q => q.Number).ToList();

        if (test.ShuffleQuestions)
        {
            var random = new Random();
            questions = questions.OrderBy(_ => random.Next()).ToList();
        }
        
        SaveQuestions(questions);
        return questions;
    }

    private void SaveQuestions(IEnumerable<Question> questions)
    {
        HttpContext.Session.SetJson("Questions", questions);
    }

    private UserResult GetUserResult(Guid testId, string userId, int totalQuestions)
    {
        var userResult = HttpContext.Session.GetJson<UserResult>("UserResult");
        if (userResult != null) return userResult;
        
        userResult = new UserResult
        {
            TestId = testId,
            UserId = userId,
            TotalQuestions = totalQuestions
        };

        return userResult;
    }
    
    private void SaveUserResult(UserResult userResult)
    {
        HttpContext.Session.SetJson("UserResult", userResult);
    }
}

CourseWork/Views/Admin/CreateTest.cshtml
@using CourseWork.Extensions
@model CourseWork.ViewModels.CreateTestViewModel

<head>
    <script src="~/js/update_test.js"></script>
    <title>Создание теста</title>
</head>
<body>
<h4>Новый тест</h4>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form class="row g-3" method="post" asp-controller="Admin" asp-action="CreateTest">
        <div class="col-12">
            <input type="hidden" id="testId" asp-for="TestId" value="@Model.TestId"/>
        </div>
        <div class="col-12">
            <label asp-for="Category" class="control-label">Категория</label>
            <input type="text" asp-for="Category" class="form-control"/>
        </div>
        <div class="col-12">
            <label asp-for="Name" class="control-label">Название</label>
            <input asp-for="Name" class="form-control"/>
        </div>
        <div class="col-12">
            <label asp-for="Description" class="control-label">Описание</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="col-12">
            <div class="form-check">
                <label class="form-check-label" asp-for="ShuffleQuestions">Перемешать вопросы</label>
                <input class="form-check-input" type="checkbox" asp-for="ShuffleQuestions" name="ShuffleQuestions"/>
            </div>
        </div>
        <div class="col-md-4">
            <label asp-for="OpenTime">Время начала теста</label>
            <input class="form-control" asp-for="OpenTime" asp-format="{0:yyyy-MM-ddTHH:mm}" value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")">
        </div>
        <div class="col-md-4">
            <label asp-for="CloseTime">Время окончания теста</label>
            <input class="form-control" asp-for="CloseTime" asp-format="{0:yyyy-MM-ddTHH:mm}" value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")">
        </div>
        <div class="col-md-4">
            <label asp-for="QuestionsLimit" class="control-label">Лимит вопросов для теста</label>
            <input id="QuestionsLimit" class="form-control" type="number" asp-for="QuestionsLimit" min="0" max="@Model.QuestionsLimit" step="1"/>
        </div>
        <div class="col-12">
            <div id="Questions"></div>
        </div>
        <div class="col-12">
            <label asp-for="Types" class="control-label">Выберите тип вопроса:</label>
        </div>
        <div class="input-group">
            <select id="questionType" name="questionType" class="form-select">
                @foreach(var questionType in Model.Types)
                {
                    <option value="@questionType">@questionType.ToFriendlyString()</option>
                }
            </select>
            <input type="button" class="btn btn-outline-primary" value="Добавить вопрос" onclick="addQuestion()"/>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a asp-action="Tests" class="btn btn-secondary">Отмена</a>
    </form>
</body>

<script>
let questionsCount = @Html.Raw(Json.Serialize(Model.Questions != null ? Model.Questions.Count : 0));

let Questions = [];

Init();

function Init() {
    if (questionsCount !== 0)
    {
        @{
        var questionsList = Model.Questions.ToList();
        for (int i = 0; i < questionsList.Count; i++)
        {
            var question = Model.Questions[i];
            @:Questions.push({
            @:Id: @Html.Raw(Json.Serialize(question.Id)),
            @:TestId: @Html.Raw(Json.Serialize(question.TestId)),
            @:Type: @Html.Raw(Json.Serialize(question.Type)),
            @:Text: @Html.Raw(Json.Serialize(question.Text)),
            @:Number: @Html.Raw(Json.Serialize(question.Number)),
            @:Cost: @Html.Raw(Json.Serialize(question.Cost)),
            @:Answers:[]        
            @:})
              
            var answersList = question.Answers.ToList();
            for (int j = 0; j < answersList.Count; j++)
            {
                var answer = question.Answers.ToList()[j];
                @:Questions[@i].Answers.push({
                @:Id: @Html.Raw(Json.Serialize(answer.Id)),
                @:QuestionId: @Html.Raw(Json.Serialize(answer.QuestionId)),
                @:IsCorrect: @Html.Raw(Json.Serialize(answer.IsCorrect)),
                @:Response: @Html.Raw(Json.Serialize(answer.Response)),
                @:CorrectResponse: @Html.Raw(Json.Serialize(answer.CorrectResponse)),
                @:Number: @Html.Raw(Json.Serialize(answer.Number)),
                @:})
            }
        }}
    }
    
    redrawQuestions();
}
</script>

CourseWork/Views/Admin/EditTest.cshtml
@using CourseWork.Extensions
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model CourseWork.ViewModels.EditTestViewModel

<head>
    <script src="~/js/update_test.js"></script>
    <title>Редактирование теста</title>
</head>
<body>
    <h4>Редактирование теста</h4>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form class="row g-3" method="post" asp-controller="Admin" asp-action="EditTest">
        <div class="col-12">
            <input type="hidden" id="testId" asp-for="TestId" value="@Model.TestId"/>
        </div>
        <div class="col-12">
            <input type="hidden" id="QuestionsCount" asp-for="QuestionsCount" value="@Model.QuestionsCount"/>
        </div>
        <div class="col-12">
            <label asp-for="Category" class="control-label">Категория</label>
            <input type="text" asp-for="Category" class="form-control"/>
        </div>
        <div class="col-12">
            <label asp-for="Name" class="control-label">Название</label>
            <input asp-for="Name" class="form-control"/>
        </div>
        <div class="col-12">
            <label asp-for="Description" class="control-label">Описание</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="col-12">
            <div class="form-check">
                <label class="form-check-label" asp-for="ShuffleQuestions">Перемешать вопросы</label>
                <input class="form-check-input" type="checkbox" asp-for="ShuffleQuestions" name="ShuffleQuestions"/>
            </div>
        </div>
        <div class="col-md-4">
            <label asp-for="OpenTime">Время начала теста</label>
            <input class="form-control" asp-for="OpenTime" asp-format="{0:yyyy-MM-ddTHH:mm}">
        </div>
        <div class="col-md-4">
            <label asp-for="CloseTime">Время окончания теста</label>
            <input class="form-control" asp-for="CloseTime" asp-format="{0:yyyy-MM-ddTHH:mm}">
        </div>
        <div class="col-md-4">
            <label asp-for="QuestionsLimit" class="control-label">Лимит вопросов для теста</label>
            <input id="QuestionsLimit" class="form-control" type="number" asp-for="QuestionsLimit" min="0" max="@Model.QuestionsCount" step="1"/>
        </div>
        <div class="col-12">
            <div id="Questions"></div>
        </div>
        <div class="col-12">
            <label asp-for="Types" class="control-label">Выберите тип вопроса:</label>
        </div>
        <div class="input-group">
            <select id="questionType" name="questionType" class="form-select">
                @foreach(var questionType in Model.Types)
                {
                    <option value="@questionType">@questionType.ToFriendlyString()</option>
                }
            </select>
            <input type="button" class="btn btn-outline-primary" value="Добавить вопрос" onclick="addQuestion()"/>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a asp-action="Tests" class="btn btn-secondary">Отмена</a>
    </form>
</body>

<script>
let questionsCount = @Html.Raw(Json.Serialize(Model.Questions != null ? Model.Questions.Count : 0));

let Questions = [];

Init();

function Init() {
    if (questionsCount !== 0)
    {
        @{
        var questionsList = Model.Questions.ToList();
        for (int i = 0; i < questionsList.Count; i++)
        {
            var question = Model.Questions[i];
            @:Questions.push({
            @:Id: @Html.Raw(Json.Serialize(question.Id)),
            @:TestId: @Html.Raw(Json.Serialize(question.TestId)),
            @:Type: @Html.Raw(Json.Serialize(question.Type)),
            @:Text: @Html.Raw(Json.Serialize(question.Text)),
            @:Number: @Html.Raw(Json.Serialize(question.Number)),
            @:Cost: @Html.Raw(Json.Serialize(question.Cost)),
            @:Answers:[]        
            @:})
              
            var answersList = question.Answers.ToList();
            for (int j = 0; j < answersList.Count; j++)
            {
                var answer = question.Answers.ToList()[j];
                @:Questions[@i].Answers.push({
                @:Id: @Html.Raw(Json.Serialize(answer.Id)),
                @:QuestionId: @Html.Raw(Json.Serialize(answer.QuestionId)),
                @:IsCorrect: @Html.Raw(Json.Serialize(answer.IsCorrect)),
                @:Response: @Html.Raw(Json.Serialize(answer.Response)),
                @:CorrectResponse: @Html.Raw(Json.Serialize(answer.CorrectResponse)),
                @:Number: @Html.Raw(Json.Serialize(answer.Number)),
                @:})
            }
        }}
    }
    
    redrawQuestions();
}
</script>

CourseWork/Views/Admin/Tests.cshtml
@model IQueryable<Test>

<!doctype html>
<html lang="en">
<head>
    <title>Тесты</title>
</head>
<body>
    <h4>Список тестов</h4>
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

    @if (!Model.Any())
    {
        <li class="list-group-item">Тестов нет</li>
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Название теста</th>
                    <th scope="col">Категория</th>
                    <th scope="col">Уведомления</th>
                    <th scope="col">Информация</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            @{var counter = 0;    
                foreach (var test in Model)
                {
                    counter++;
                    <tr>
                        <th scope="row">@counter</th>
                        <td>@test.Name</td>
                        <td>@test.Category</td>
                        <td>
                            <a class="btn btn-sm btn-outline-primary" asp-route-testId="@test.Id" asp-controller="Notification" asp-action="ConfigureNotifications">Настроить</a>
                        </td>
                        <td>
                            <a class="btn btn-sm btn-outline-primary" asp-route-testId="@test.Id" asp-controller="Admin" asp-action="EditTest">Редактировать</a>
                        </td>
                        <td>
                            <a class="btn btn-sm btn-outline-danger" asp-route-testId="@test.Id" asp-controller="Admin" asp-action="DeleteTest">Удалить</a>
                        </td>
                    </tr>
                }
            }
            </tbody>
        </table>
    }
    <a class="btn btn-primary" asp-controller="Admin" asp-action="CreateTest">Создать тест</a>
</body>
</html>