CourseWork/Controllers/StatisticsController.cs
using CourseWork.Models;
using CourseWork.Services;
using CourseWork.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

public class StatisticsController : Controller
{
    private readonly IUserResultService _userResultService;
    private readonly IUserAnswerService _userAnswerService;
    private readonly IAnswerService _answerService;
    private readonly ITestService _testService;
    private readonly IQuestionService _questionService;
    private readonly UserManager<User> _userManager;

    public StatisticsController(IUserResultService userResultService, UserManager<User> userManager, ITestService testService, IUserAnswerService userAnswerService, IQuestionService questionService, IAnswerService answerService)
    {
        _userResultService = userResultService;
        _userManager = userManager;
        _testService = testService;
        _userAnswerService = userAnswerService;
        _questionService = questionService;
        _answerService = answerService;
    }

    public IActionResult UserStatistics(Guid? userId = null)
    {
        var id = userId == null ? _userManager.GetUserId(HttpContext.User) : userId.ToString();
        var userResults = _userResultService.UserResults.Where(t => t.UserId == id).OrderBy(r => r.RightPercent).ToList();

        foreach (var userResult in userResults)
        {
            userResult.Test = _testService.Tests.FirstOrDefault(t => t.Id == userResult.TestId);
        }
        return View(userResults);
    }

    public IActionResult UserResultInfo(Guid userResultId)
    {
        return View(GetUserResultInfoModel(userResultId));
    }
    
    public IActionResult UserResultInfoWithAnswers(Guid userResultId)
    {
        if (!User.IsInRole("tutor") && !User.IsInRole("admin"))
        {
            return RedirectToAction("Index", "Test");
        }
        return View(GetUserResultInfoModel(userResultId));
    }

    private UserResultViewModel GetUserResultInfoModel(Guid userResultId)
    {
        var userResult = _userResultService.UserResults.First(r => r.Id == userResultId);
        userResult.Test = _testService.Tests.FirstOrDefault(t => t.Id == userResult.TestId);
        userResult.UserAnswers = _userAnswerService.UserAnswers.Where(a => a.UserResultId == userResult.Id).OrderBy(a => a.QuestionNumber).ThenBy(a => a.AnswerNumber).ToList();
        var questions = _questionService.Questions.Where(q => q.TestId == userResult.TestId).OrderBy(q => q.Number).ToList();

        var model = new UserResultViewModel
        {
            UserResult = userResult,
            Questions = new List<Question>()
        };
        
        foreach (var question in questions)
        {
            foreach (var userAnswer in userResult.UserAnswers)
            {
                if (userAnswer.QuestionNumber == question.Number)
                {
                    model.Questions.Add(question);
                    model.Questions[^1].Answers = new List<Answer>(_answerService.Answers.Where(a => a.QuestionId == question.Id)).OrderBy(a => a.Number);
                    break;
                }
            }
        }
        
        return model;
    }

    public IActionResult UsersStatistics()
    {
        var users = _userManager.GetUsersInRoleAsync("student").Result;
        users = users.OrderBy(u => u.UserName).ThenBy(u => u.Group).ToList();
        return View(users.ToList());
    }

    public IActionResult TestStatistics(Guid? testId = null)
    {
        var userResults = _userResultService.UserResults.Where(r => r.TestId == testId).ToList();
        foreach (var userResult in userResults)
        {
            userResult.User = _userManager.Users.FirstOrDefault(u => u.Id == userResult.UserId);
        }
        return View(userResults);
    }
}

CourseWork/Views/Statistics/TestStatistics.cshtml
@model List<CourseWork.Models.UserResult>

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="ru">
<head>
    <title>Статистика по тесту</title>
</head>
<body>
<div>
      <table class="table">
          <thead>
          <tr>
              <th scope="col">№</th>
              <th scope="col">Имя пользователя</th>
              <th scope="col">Email</th>
              <th scope="col">Время начала</th>
              <th scope="col">Время окончания</th>
              <th scope="col">Отвечено вопросов</th>
              <th scope="col">Результат</th>
              <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
              @{
                  var counter = 0;
                  foreach (var userResult in Model)
                  {
                      counter++;
                      <tr>
                          <th scope="row">@counter</th>
                          <td>@userResult.User?.UserName</td>
                          <td>@userResult.User?.Email</td>
                          <td>@userResult.BeginTime</td>
                          <td>@userResult.EndTime</td>
                          <td>@userResult.CompletedQuestions/@userResult.TotalQuestions</td>
                          <td>@Math.Round(userResult.RightPercent * 100, 2)</td>
                          <td>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-route-userResultId="@userResult.Id" asp-action="UserResultInfoWithAnswers">Подробнее</a>
                        </td>
                      </tr>
                  }
              }
              </tbody>
      </table>
</div>
</body>
</html>

CourseWork/Views/Statistics/UserResultInfo.cshtml
@using CourseWork.Models.Enums
@model CourseWork.ViewModels.UserResultViewModel

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="ru">
<head>
    <title>Просмотр ответов</title>
</head>
<body>
    <div>
        @await Html.PartialAsync("TestInfoDetailedPartial", Model)
        @if (!Model.UserResult.UserAnswers.Any())
        {
            <li class="list-group-item">Отвеченных вопросов нет</li>
        }
        else
        {
            var userAnswers = Model.UserResult.UserAnswers.ToList();
            for (int k = 0, j = 0; k < Model.Questions.Count; k++)
            {
                <br>
                <h6>Вопрос @(k + 1):</h6>
                <p>@Model.Questions[k].Text</p>
                switch (Model.Questions[k].Type)
                {
                    case QuestionType.FreeEntry:
                    {
                        <input type="text" class="form-control" value="@userAnswers[j++].AnswerText" readonly>
                    }
                        break;
                    case QuestionType.WithAnswerOptions:
                    {
                        var answers = Model.Questions[k].Answers.ToList();
                        var singleResponse = answers.Count(a => a.IsCorrect) == 1;
                        for (var i = 0; i < answers.Count; i++)
                        {
                            if (singleResponse)
                            {
                                <div class="input-group">
                                    <div class="form-check">
                                        @if (userAnswers[j++].IsCorrect)
                                        {
                                            <input class="form-check-input" type="radio" value="@answers[i].Response" checked disabled>
                                        }
                                        else
                                        {
                                            <input class="form-check-input" type="radio" value="@answers[i].Response" disabled>
                                        }
                                        <label class="form-check-label">@answers[i].Response</label>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="input-group">
                                    <div class="form-check">
                                        @if (userAnswers[j++].IsCorrect)
                                        {
                                            <input class="form-check-input" type="checkbox" checked disabled/>
                                        }
                                        else
                                        {
                                            <input class="form-check-input" type="checkbox" disabled/>
                                        }
                                        <label class="form-check-label">@answers[i].Response</label>
                                    </div>
                                </div>
                            }
                        }
                    }
                        break;
                }
            }
        }
    </div>
</body>
</html>

CourseWork/Views/Statistics/UserResultInfoWithAnswers.cshtml
@using CourseWork.Models.Enums
@model CourseWork.ViewModels.UserResultViewModel

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="ru">
<head>
    <title>Просмотр ответов</title>
</head>
<body>
<div>
    @await Html.PartialAsync("TestInfoDetailedPartial", Model)
    @if (!string.IsNullOrEmpty(Model.UserResult.UserComment))
    {
        <label>Комментарий пользователя:</label>
        <input type="text" style="background-color:lightblue;" class="form-control" value="@Model.UserResult.UserComment" readonly>
    }

    @if (!Model.UserResult.UserAnswers.Any())
    {
        <li class="list-group-item">Отвеченных вопросов нет</li>
    }
    else
    {
        var userAnswers = Model.UserResult.UserAnswers.ToList();
        for (int k = 0, j = 0; k < Model.Questions.Count; k++)
        {
            <br>
            <h6>Вопрос @(k + 1):</h6>
            <p>@Model.Questions[k].Text</p>
            switch (Model.Questions[k].Type)
            {
                case QuestionType.FreeEntry:
                {
                    var correctResponse = Model.Questions[k].Answers.ToList()[0].CorrectResponse;
                    if (correctResponse.Equals(userAnswers[j].AnswerText))
                    {
                        <input type="text" style="background-color:lightgreen;" class="form-control" value="@userAnswers[j++].AnswerText" readonly>
                    }
                    else
                    {
                        <input type="text" style="background-color:indianred;" class="form-control" value="@userAnswers[j++].AnswerText" readonly>
                        <input type="text" class="form-control" value="@correctResponse" readonly>
                    }
                }
                    break;
                case QuestionType.WithAnswerOptions:
                {
                    var answers = Model.Questions[k].Answers.ToList();
                    var singleResponse = answers.Count(a => a.IsCorrect) == 1;
                    for (var i = 0; i < answers.Count; i++)
                    {
                        if (singleResponse)
                        {
                            <div class="input-group">
                                <div class="form-check">
                                    @if (userAnswers[j++].IsCorrect)
                                    {
                                        if (answers[i].IsCorrect)
                                        {
                                            <input style="background-color:lightgreen;" class="form-check-input" type="radio" value="@answers[i].Response" checked disabled>
                                        }
                                        else
                                        {
                                            <input style="background-color:indianred;" class="form-check-input" type="radio" value="@answers[i].Response" checked disabled>
                                        }
                                    }
                                    else
                                    {
                                        if (answers[i].IsCorrect)
                                        {
                                            <input style="background-color:indianred;" class="form-check-input" type="radio" value="@answers[i].Response" disabled>
                                        }
                                        else
                                        {
                                            <input style="background-color:lightgreen;" class="form-check-input" type="radio" value="@answers[i].Response" disabled>
                                        }
                                    }
                                    <label class="form-check-label">@answers[i].Response</label>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="input-group">
                                <div class="form-check">
                                    @if (userAnswers[j++].IsCorrect)
                                    {
                                        if (answers[i].IsCorrect)
                                        {
                                            <input style="background-color:lightgreen;" class="form-check-input" type="checkbox" checked disabled/>
                                        }
                                        else
                                        {
                                            <input style="background-color:indianred;" class="form-check-input" type="checkbox" checked disabled/>
                                        }
                                    }
                                    else
                                    {
                                        if (answers[i].IsCorrect)
                                        {
                                            <input style="background-color:indianred;" class="form-check-input" type="checkbox" disabled/>
                                        }
                                        else
                                        {
                                            <input style="background-color:lightgreen;" class="form-check-input" type="checkbox" disabled/>
                                        }
                                    }
                                    <label class="form-check-label">@answers[i].Response</label>
                                </div>
                            </div>
                        }
                    }
                }
                    break;
            }
            <p><b>Время ответа:</b> @userAnswers[j - 1].AnswerTime</p>
            <p><b>Стоимость вопроса:</b> @Model.Questions[k].Cost</p>
        }
    }
</div>
</body>
</html>

CourseWork/Views/Statistics/UserStatistics.cshtml
@model List<UserResult>

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="ru">
<head>
    <title>Статистика пользователей</title>
</head>
<body>
<div>
      @if (!Model.Any())
      {
         <li class="list-group-item">Пройденных тестов нет</li>
      }
      else
      {
          <table class="table">
              <thead>
              <tr>
                  <th scope="col">№</th>
                  <th scope="col">Название теста</th>
                  <th scope="col">Время начала</th>
                  <th scope="col">Время окончания</th>
                  <th scope="col">Правильно отвечено</th>
                  <th scope="col">Оценка</th>
                  <th scope="col"></th>
              </tr>
              </thead>
              <tbody>
              @{
                  var counter = 0;
                  foreach (var userResult in Model)
                  {
                      counter++;
                      <tr>
                          <th scope="row">@counter</th>
                          <td>@userResult.Test?.Name</td>
                          <td>@userResult.BeginTime</td>
                          <td>@userResult.EndTime</td>
                          <td>@Math.Round(userResult.RightPercent * 100, 2) %</td>
                          <td>@Math.Round(userResult.RightPercent * 10)</td>
                          @if (User.IsInRole("tutor") || User.IsInRole("admin"))
                          {
                              <td>
                                  <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-route-userResultId="@userResult.Id" asp-action="UserResultInfoWithAnswers">Подробнее</a>
                              </td>
                          }
                          else
                          {
                              <td>
                                  <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-route-userResultId="@userResult.Id" asp-action="UserResultInfo">Подробнее</a>
                              </td>
                          }
                      </tr>
                  }
              }
              </tbody>
          </table>
      }
</div>
</body>
</html>

CourseWork/Views/Statistics/UsersStatistics.cshtml
@model List<CourseWork.Models.User>

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html lang="ru">
<head>
    <title>Статистика пользователей</title>
</head>
<body>
<div>
      <table class="table">
          <thead>
          <tr>
              <th scope="col">№</th>
              <th scope="col">Имя пользователя</th>
              <th scope="col">Email</th>
              <th scope="col">Группа</th>
              <th scope="col">Статистика</th>
          </tr>
          </thead>
          <tbody>
              @{
                  var counter = 0;
                  foreach (var user in Model)
                  {
                      counter++;
                      <tr>
                          <th scope="row">@counter</th>
                          <td>@user.UserName</td>
                          <td>@user.Email</td>
                          <td>@user.Group</td>
                          <td>
                              <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-route-userId="@user.Id" asp-action="UserStatistics">Подробнее</a>
                          </td>
                      </tr>
                  }
              }
              </tbody>
      </table>
</div>
</body>
</html>