CourseWork/Controllers/AdminController.cs
using System.Transactions;
using CourseWork.Models;
using CourseWork.Services;
using CourseWork.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

[Authorize(Roles="admin, tutor")]
public class AdminController : Controller
{
    private readonly ITestService _testService;
    private readonly IQuestionService _questionService;
    private readonly IAnswerService _answerService;
    
    public AdminController(ITestService testService, IQuestionService questionService, IAnswerService answerService)
    {
        _testService = testService;
        _questionService = questionService;
        _answerService = answerService;
    }
    
    public IActionResult Tests() => View(_testService.Tests);

    [HttpGet]
    public IActionResult CreateTest()
    {
        return View(new CreateTestViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> CreateTest(CreateTestViewModel model)
    {
        if (!ModelState.IsValid) return View(model);
        
        var test = new Test 
        { 
            Id = model.TestId,
            Category = model.Category, Name = model.Name, 
            Description = model.Description, OpenTime = model.OpenTime, 
            CloseTime = model.CloseTime, QuestionsCount = model.Questions.Count,
            QuestionsLimit = model.QuestionsLimit,
            ShuffleQuestions = model.ShuffleQuestions,
            Questions = model.Questions.AsEnumerable()
        };

        await _testService.AddAsync(test);
        return RedirectToAction("Tests");
    }
    
    [HttpGet]
    public async Task<IActionResult> EditTest(Guid? testId)
    {
        if (testId == null) return NotFound();
        var test = await _testService.GetByIdAsync(testId);
        if (test == null) return NotFound();
        var model = new EditTestViewModel
        {
            TestId = test.Id,
            Category = test.Category, Name = test.Name,
            Description = test.Description,
            OpenTime = test.OpenTime, CloseTime = test.CloseTime,
            QuestionsLimit = test.QuestionsLimit,
            QuestionsCount = test.QuestionsCount,
            ShuffleQuestions = test.ShuffleQuestions,
            Questions = _questionService.Questions.Where(q => q.TestId == test.Id).OrderBy(q => q.Number).ToList(),
        };
        
        foreach (var question in model.Questions)
        {
            question.Answers = _answerService.Answers.Where(a => a.QuestionId == question.Id).OrderBy(a => a.Number).ToList();
        }
        return View(model);
    }
    
    [HttpPost]
    public async Task<IActionResult> EditTest(EditTestViewModel model)
    {
        if (!ModelState.IsValid) return View(model);
        var test = await _testService.GetByIdAsync(model.TestId);
        if (test == null) return View(model);
        
        using (var scope = new TransactionScope(
                   TransactionScopeAsyncFlowOption.Enabled))
        {
            await _testService.DeleteAsync(test.Id).ConfigureAwait(false);
            scope.Complete();
        }
        
        test.Category = model.Category;
        test.Name = model.Name;
        test.Description = model.Description;
        test.OpenTime = model.OpenTime;
        test.CloseTime = model.CloseTime;
        test.QuestionsLimit = model.QuestionsLimit;
        test.QuestionsCount = model.Questions.Count;
        test.Questions = model.Questions.AsEnumerable();
        test.ShuffleQuestions = model.ShuffleQuestions;

        using (var scope = new TransactionScope(
                   TransactionScopeAsyncFlowOption.Enabled))
        {
            await _testService.AddAsync(test).ConfigureAwait(false);
            scope.Complete();
        }

        return RedirectToAction("Tests");
    }
    
    public async Task<IActionResult> DeleteTest(Guid? testId)
    {
        if (testId == null) return NotFound();
        await _testService.DeleteAsync(testId);
        return RedirectToAction("Tests");
    }
}

CourseWork/Controllers/RolesController.cs
using CourseWork.Models;
using CourseWork.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
    
namespace CourseWork.Controllers;

[Authorize(Roles="admin")]
public class RolesController : Controller
{
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly UserManager<User> _userManager;
    
    public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
    {
        _roleManager = roleManager;
        _userManager = userManager;
    }

    public IActionResult Index()
    {
        return View(_roleManager.Roles.ToList());
    }

    public IActionResult Create()
    {
        return View();
    } 
    
    [HttpPost]
    public async Task<IActionResult> Create(string name)
    {
        if (string.IsNullOrEmpty(name)) 
            return View(name);
        
        var result = await _roleManager.CreateAsync(new IdentityRole(name));
        if (result.Succeeded)
        {
            return RedirectToAction("Index");
        }

        foreach (var error in result.Errors)
        {
            ModelState.AddModelError(string.Empty, error.Description);
        }
        return View(name);
    }
     
    [HttpPost]
    public async Task<IActionResult> Delete(string testId)
    {
        var role = await _roleManager.FindByIdAsync(testId);
        if (role != null)
        {
            await _roleManager.DeleteAsync(role);
        }
        return RedirectToAction("Index");
    }

    public IActionResult UserList()
    {
        return View(_userManager.Users.Where(u => !u.UserName.Equals("admin")));
    } 

    public async Task<IActionResult> Edit(string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null) 
            return NotFound();
        
        var userRoles = await _userManager.GetRolesAsync(user);
        var allRoles = _roleManager.Roles.ToList();
        var model = new ChangeRoleViewModel
        {
            UserId = user.Id,
            UserEmail = user.Email,
            UserRoles = userRoles,
            AllRoles = allRoles
        };
        return View(model);

    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(string userId, List<string> roles)
    {
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null) 
            return NotFound();
        
        var userRoles = await _userManager.GetRolesAsync(user);
        var addedRoles = roles.Except(userRoles);
        var removedRoles = userRoles.Except(roles);

        await _userManager.AddToRolesAsync(user, addedRoles);
        await _userManager.RemoveFromRolesAsync(user, removedRoles);

        return RedirectToAction("UserList");
    }
}

CourseWork/Controllers/TestController.cs
using CourseWork.Extensions;
using CourseWork.Models;
using CourseWork.Services;
using CourseWork.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

[Authorize]
public class TestController : Controller
{
    private readonly ITestService _testService;
    private readonly IAnswerService _answerService;
    private readonly IQuestionService _questionService;
    private readonly IUserResultService _userResultService;
    private readonly UserManager<User> _userManager;
    
    public TestController(ITestService testService, IAnswerService answerService, 
        UserManager<User> userManager, IQuestionService questionService, IUserResultService userResultService)
    {
        _testService = testService;
        _answerService = answerService;
        _userManager = userManager;
        _questionService = questionService;
        _userResultService = userResultService;
    }

    public IActionResult Index()
    {
        var tests = _testService.Tests.OrderByDescending(t => t.OpenTime).ToList();
        var sorted = tests.Where(t => DateTime.Now < t.CloseTime).OrderBy(t => t.OpenTime).ToList();
        sorted.AddRange(tests.Where(t => DateTime.Now > t.CloseTime).OrderByDescending(t => t.OpenTime).ToList());
        return View(sorted);
    }

    public async Task<IActionResult> TestInfo(Guid? testId) => View(await _testService.GetByIdAsync(testId));

    public async Task<IActionResult> Testing(Guid testId, QuestionViewModel model, int currentPage = 1)
    {
        var test = await _testService.GetByIdAsync(testId);
        if (test == null)
        {
            return RedirectToAction("Index", "Home");
        }
        
        if (DateTime.Now < test.OpenTime || DateTime.Now > test.CloseTime)
        {
            TempData["error-message"] = "В доступе отказано";
            return RedirectToAction("TestInfo", new {testId = test.Id});
        }

        if (model.UserAnswers.Any() && model.Answers.Any())
        {
            if (model.SelectedUserAnswerId != null)
            {
                model.UserAnswers
                    .Where(a => a.Id == model.SelectedUserAnswerId)
                    .ToList().ForEach(a => a.IsCorrect = true);
            }
            UpdateUserResult(model.UserAnswers, model.Answers, test, model.Question.Cost);
        }

        const int pageSize = 1;
        var questions = GetQuestions(test);
        var question = questions.Skip((currentPage - 1) * pageSize).Take(pageSize).FirstOrDefault();
        if (question == null)
        {
            return RedirectToAction("Error", "Home");
        }
        var answers = _answerService.Answers.Where(a => a.QuestionId == question.Id).ToList();
        var userAnswers = new List<UserAnswer>();
        
        for (var i = 0; i < answers.Count; i++)
        {
            userAnswers = userAnswers.Append(new UserAnswer
            {
                QuestionNumber = question.Number
            }).ToList();
        }
        
        return View(new QuestionViewModel
        {
            Question = question, 
            UserAnswers = userAnswers,
            Answers = answers,
            TestCloseTime = test.CloseTime,
            PageViewModel = new PageViewModel(test.QuestionsLimit, currentPage, pageSize)
        });
    }

    public void UpdateUserResult(List<UserAnswer> userAnswers, List<Answer> correctAnswers, Test test, int cost)
    {
        var userId = _userManager.GetUserId(HttpContext.User);
        var userResult = GetUserResult(test.Id, userId, test.QuestionsLimit);
        userResult.AddAnswers(userAnswers, correctAnswers, cost);
        SaveUserResult(userResult);
    }

    public async Task<IActionResult> EndTesting(QuestionViewModel model)
    {
        var test = await _testService.GetByIdAsync(model.Question.TestId);
        if (test == null)
        {
            return RedirectToAction("Index", "Home");
        }

        UpdateUserResult(model.UserAnswers, model.Answers, test, model.Question.Cost);

        var userId = _userManager.GetUserId(HttpContext.User);
        var userResult = GetUserResult(model.Question.TestId, userId, test.QuestionsLimit);
        await _userResultService.AddAsync(userResult);
        HttpContext.Session.Clear();
        ViewData["userResultId"] = userResult.Id;
        return View(userResult);
    }

    [HttpPost]
    public IActionResult BackToTests(Guid userResultId, string? comment)
    {
        if (string.IsNullOrEmpty(comment?.Trim())) 
            return RedirectToAction("Index");
        
        var userResult = _userResultService.UserResults.FirstOrDefault(r => r.Id == userResultId);
        if (userResult != null)
        {
            userResult.UserComment = comment;
            _userResultService.UpdateAsync(userResult);
        }
        return RedirectToAction("Index");
    }
    
    private IEnumerable<Question> GetQuestions(Test test)
    {
        var questions = HttpContext.Session.GetJson<IEnumerable<Question>>("Questions");
        if (questions != null) return questions;

        questions = _questionService.Questions.Where(q => q.TestId == test.Id).OrderBy(q => q.Number).ToList();

        if (test.ShuffleQuestions)
        {
            var random = new Random();
            questions = questions.OrderBy(_ => random.Next()).ToList();
        }
        
        SaveQuestions(questions);
        return questions;
    }

    private void SaveQuestions(IEnumerable<Question> questions)
    {
        HttpContext.Session.SetJson("Questions", questions);
    }

    private UserResult GetUserResult(Guid testId, string userId, int totalQuestions)
    {
        var userResult = HttpContext.Session.GetJson<UserResult>("UserResult");
        if (userResult != null) return userResult;
        
        userResult = new UserResult
        {
            TestId = testId,
            UserId = userId,
            TotalQuestions = totalQuestions
        };

        return userResult;
    }
    
    private void SaveUserResult(UserResult userResult)
    {
        HttpContext.Session.SetJson("UserResult", userResult);
    }
}

CourseWork/Views/Shared/TestInfoBriefPartial.cshtml
@model Test

<h4>@Model.Name</h4>
<dl class="row">
    <dt class="col-sm-3">Категория:</dt>
    <dd class="col-sm-9">@Model.Category</dd>
    
    <dt class="col-sm-3">Описание:</dt>
    <dd class="col-sm-9"><p>@Model.Description</p></dd>
    
    <dt class="col-sm-3">Время начала тестирования:</dt>
    <dd class="col-sm-9">@Model.OpenTime</dd>
    
    <dt class="col-sm-3">Время окончания тестирования:</dt>
    <dd class="col-sm-9">@Model.CloseTime</dd>
</dl>

CourseWork/Views/Shared/TestInfoDetailedPartial.cshtml
@model CourseWork.ViewModels.UserResultViewModel

@{
    var maxScore = Model.Questions.Sum(q => q.Cost);
}

<h4>@Model.UserResult.Test.Name</h4>
<dl class="row">
    <dt class="col-sm-3">Категория:</dt>
    <dd class="col-sm-9">@Model.UserResult.Test.Category</dd>
        
    <dt class="col-sm-3">Описание:</dt>
    <dd class="col-sm-9"><p>@Model.UserResult.Test.Description</p></dd>
        
    <dt class="col-sm-3">Время начала тестирования:</dt>
    <dd class="col-sm-9">@Model.UserResult.BeginTime</dd>
        
    <dt class="col-sm-3">Время окончания тестирования:</dt>
    <dd class="col-sm-9">@Model.UserResult.EndTime</dd>
        
    <dt class="col-sm-3">Отвечено вопросов:</dt>
    <dd class="col-sm-9">@Model.UserResult.TotalQuestions/@Model.UserResult.TotalQuestions</dd>
        
    <dt class="col-sm-3">Получено баллов:</dt>
    <dd class="col-sm-9">@Model.UserResult.Score/@maxScore</dd>
        
    <dt class="col-sm-3">Оценка:</dt>
    <dd class="col-sm-9">@Math.Round(Model.UserResult.RightPercent * 10)</dd>
</dl>

CourseWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - testingsystems</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CourseWork.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">testingsystems</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Тесты</a>
                    </li>
                    @if (User.IsInRole("student"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="UserStatistics">Статистика</a>
                        </li>
                    }
                    @if (User.IsInRole("tutor") || User.IsInRole("admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Tests">Управление тестами</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="UsersStatistics">Статистика пользователей</a>
                        </li>
                    }
                    @if (User.IsInRole("admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Управление ролями</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suggestion" asp-action="Suggestions">Предложения</a>
                        </li> 
                    }

                    @if(User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item" style="margin-left: auto; margin-right: 0">
                            <a class="nav-link text-dark">@User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input class="btn btn-dark" type="submit" value="Выход" />
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item" style="margin-left: auto; margin-right: 0">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - testingsystems - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>